### ISSUE TITLE
Determine Workflow Manager migration

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/geodatabase-taxmap-toiler#1]
There are workflow manager tables in both the JTX schema and in the DOF_TAXMAP schema.  

Which (if any) need to be migrated?  What is the best way to migrate workflow manager, does ESRI provide tools or will a simple schema expdp/impdp work?

**Comment by mattyschell** [comment]
The tables in the JTX schema need to be migrated.  Any workflow manager tables in DOF_TAXMAP are artifacts from a test.

We still need to determine if the history from the JTX schema needs to be migrated.  And if so, how do we migrate?  Is this a expdp/impdp operation or an ESRI operation.

**Comment by mrahman-doitt** [comment]
If I remember correctly, Workflow Manager provides few tools to export/import jobs and configurations. May be you can provide Andy  an empty JTX schema, he can use WM tool to populate them from 11G database.  

![image](https://user-images.githubusercontent.com/16340672/154155700-00e4cb0d-4973-49de-b3c5-95b93eecc7c0.png)

**Comment by mattyschell** [comment]
Looks like it is actually JTX_ADMIN, not JTX.

The legacy production schema holds around 5 GB of data.  Let's start with empty JTX_ADMIN and 10GB.

**Comment by mattyschell** [comment]
> This would work for Workflow manager. Workflow manager generates the tables associated with this schema once a default database is added to the workflow manager administrator but if there are empty tables once I add the jtx information in the workflow manager administrator, it would pick it up. If this doesn’t work, then we an remove the tables and let the workflow manager administrator simply connect to the new DB and create the schema in the tables brand new. But on its face I don’t see any issues with the proposed solution.

**Comment by mattyschell** [comment]
https://github.com/mattyschell/geodatabase-taxmap-toiler/blob/main/doc/jtx_admin.md
