### ISSUE TITLE
Workflow Manager Tables are missing

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/geodatabase-taxmap-toiler#13]
This is not an issue for this repository to manage, unless it is.

Whatever process is creating workflow manager tables in JTX_ADMIN is not creating JTX_ADMIN.JTX_TRANSACTION_SESSIONS.  Consider adding it to this repo so we can avoid issues in future setup.

**Comment by Greatness846** [comment]
Found another missing Table as well. JTX_ADMIN.JTX_LAYERS

**Comment by mattyschell** [comment]
Closed with a7df2f256a21a88cb47b31d7b520a986dab70ef0.  Add more to the jtx tables list as needed.
